#!/bin/bash
set -euo pipefail

: "${SCODE_COVERAGE_TARGET:?missing SCODE_COVERAGE_TARGET}"
: "${SCODE_COVERAGE_DIR:?missing SCODE_COVERAGE_DIR}"
: "${SCODE_KCOV_BINARY:?missing SCODE_KCOV_BINARY}"

exec "$SCODE_KCOV_BINARY" \
  --include-path="$SCODE_COVERAGE_TARGET" \
  --exclude-region='SCODE_COVERAGE_STATIC_START:SCODE_COVERAGE_STATIC_END' \
  "$SCODE_COVERAGE_DIR" \
  "$SCODE_COVERAGE_TARGET" \
  "$@"
